POS/Controllers/CreditoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Models;
using POS.Fn;

namespace POS.Controllers
{
    public class CreditoController : Controller
    {

        moragas_pruebasEntities1 db = new moragas_pruebasEntities1();

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Creditos Por Cliente")]
        public ViewResult Index()
        {
            List<int> ListaSucursalesPermitidas = Fn.usuario_logeado.Sucursales_id();
            ViewBag.id_sucursal = new SelectList(db.sucursal.Where(x => ListaSucursalesPermitidas.Contains(x.id)).OrderByDescending(y => y.id), "id", "nombre_sucursal");
            return View();
        }

        public PartialViewResult VistaParcialCreditoCliente(int id_sucursal)
        {
            List<int> ListaIdsClientes = db.multiple_pago.Where(x => x.id_tipo_pago_venta == 4).Select(y => y.venta.Cliente_id).ToList();
            List<cliente> ListaCreditosClientes = db.cliente.Where(x => x.venta.Where(y => y.multiple_pago.Where(z => z.id_tipo_pago_venta == 4).Any() && y.catalogo_status_id != 2 && y.catalogo_status_id != 12 && y.sucursal_id == id_sucursal).Count() > 0).ToList();
            ViewBag.ListaCreditosClientes = ListaCreditosClientes;
            return PartialView();
        }

        public ActionResult VistaEditarDiasCredito(int id, int ruta)
        {
            ViewBag.id = id;
            ViewBag.ruta = ruta;
            return View("EditarDiasCredito", db.cliente.Find(id));
        }

        [HttpPost]
        public ActionResult EditarDiasCredito(int id, int dias, int ruta)
        {
            cliente cliente = db.cliente.Find(id);
            cliente.dias_credito = dias;
            db.Entry(cliente).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            if (ruta == 1)
                return RedirectToAction("Index");
            else
                return RedirectToAction("MostrarCreditosClientes", new { id = id });
        }

        [Authorize]
        public ViewResult MostrarCreditosClientes(int id)
        {
            cliente c = db.cliente.Find(id);
            ViewBag.nombre = c.Razon_social;
            ViewBag.id = id;
            return View(c);
        }

        public PartialViewResult MostrarCreditosClientesVistaParcial(int id, bool solamente_pendientes)
        {
            cliente c = db.cliente.Find(id);
            List<venta> listaVentasCreditoCliente = new List<venta>();
            if (solamente_pendientes)
                listaVentasCreditoCliente = db.venta.Where(x => x.Cliente_id == id && x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && x.aduedo.Value != 0 && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
            else
                listaVentasCreditoCliente = db.venta.Where(x => x.Cliente_id == id && x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
            ViewBag.nombre = c.Razon_social;
            return PartialView(listaVentasCreditoCliente);
        }

        public PartialViewResult MostrarNotasCreditoClientesVistaParcial(int id, bool solamente_pendientes)
        {
            cliente c = db.cliente.Find(id);
            List<nota_credito> listaNotasCredito = new List<nota_credito>();
            if (solamente_pendientes)
            {
                List<int> ListaIdsVentas = c.venta.Where(x => x.nota_credito.Where(y => y.id_estatus_nota_credito == 1).Any()).Select(x => x.id).ToList();
                listaNotasCredito = db.nota_credito.Where(x => ListaIdsVentas.Contains(x.id_venta) && x.id_estatus_nota_credito == 1).ToList();
            }
            else
            {
                List<int> ListaIdsVentas = c.venta.Where(x => x.nota_credito.Any()).Select(x => x.id).ToList();
                listaNotasCredito = db.nota_credito.Where(x => ListaIdsVentas.Contains(x.id_venta)).ToList();
            }
            ViewBag.nombre = c.Razon_social;
            return PartialView(listaNotasCredito);
        }

        public PartialViewResult MostrarCreditosClientesExcelVistaParcial(int id, bool solamente_pendientes)
        {
            cliente c = db.cliente.Find(id);
            List<venta> listaVentasCreditoCliente = new List<venta>();
            List<nota_credito> ListaNotasCredito = new List<nota_credito>();
            if (solamente_pendientes)
            {
                listaVentasCreditoCliente = db.venta.Where(x => x.Cliente_id == id && x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && x.aduedo.Value != 0 && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
                List<int> ListaIdsVentas = c.venta.Where(x => x.nota_credito.Where(y => y.id_estatus_nota_credito == 1).Any()).Select(x => x.id).ToList();
                ListaNotasCredito = db.nota_credito.Where(x => ListaIdsVentas.Contains(x.id_venta) && x.id_estatus_nota_credito == 1).ToList();
            }
            else
            {
                listaVentasCreditoCliente = db.venta.Where(x => x.Cliente_id == id && x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
                List<int> ListaIdsVentas = c.venta.Where(x => x.nota_credito.Any()).Select(x => x.id).ToList();
                ListaNotasCredito = db.nota_credito.Where(x => ListaIdsVentas.Contains(x.id_venta)).ToList();
            }
            ViewBag.nombre = c.Razon_social;
            ViewBag.ListaNotasCredito = ListaNotasCredito;
            return PartialView(listaVentasCreditoCliente);
        }

        public ActionResult CancelarNotaCredito(int id, int id_cliente)
        {
            nota_credito nota_credito = db.nota_credito.Find(id);
            nota_credito.fecha_cancelacion = DateTime.Now;
            nota_credito.id_estatus_nota_credito = 3;
            db.Entry(nota_credito).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            venta venta = db.venta.Find(nota_credito.id_venta);
            movimiento_inventario movimiento_inventario = new movimiento_inventario();
            movimiento_inventario.fecha = DateTime.Now;
            movimiento_inventario.recibe = venta.cliente.Razon_social;
            movimiento_inventario.usuario_valida_id = Fn.usuario_logeado.traerUsuario().id;
            movimiento_inventario.tipo_movimiento_inventario_id = 6;
            movimiento_inventario.sucursal_id = venta.sucursal_id;
            db.movimiento_inventario.Add(movimiento_inventario);
            db.SaveChanges();
            List<concepto_por_nota_credito> ListaConceptosNotaCredito = db.concepto_por_nota_credito.Where(x => x.id_nota_credito == nota_credito.id).ToList();
            foreach (concepto_por_nota_credito concepto_por_nota_credito in ListaConceptosNotaCredito)
            {
                conceptos_por_venta concepto_venta = db.conceptos_por_venta.Find(concepto_por_nota_credito.id_conceptos_por_venta);
                inventario inventario = db.inventario.Where(x => x.Producto_id == concepto_venta.Producto_id && x.sucursal_id == venta.sucursal_id).First();
                inventario.cantidad = inventario.cantidad - concepto_por_nota_credito.cantidad;
                db.Entry(inventario).State = System.Data.Entity.EntityState.Modified;
                conceptos_por_movimiento_inventario conceptos_por_movimiento_inventario = new conceptos_por_movimiento_inventario();
                conceptos_por_movimiento_inventario.movimiento_inventario_id = movimiento_inventario.id;
                conceptos_por_movimiento_inventario.Inventario_id = inventario.id;
                conceptos_por_movimiento_inventario.cantidad = concepto_por_nota_credito.cantidad.Value;
                db.conceptos_por_movimiento_inventario.Add(conceptos_por_movimiento_inventario);
            }
            db.SaveChanges();
            return RedirectToAction("MostrarCreditosClientes", new { id = id_cliente });
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Creditos Por Venta")]
        public ViewResult HistorialCreditos()
        {
            List<int> ListaSucursalesPermitidas = Fn.usuario_logeado.Sucursales_id();
            ViewBag.id_sucursal = new SelectList(db.sucursal.Where(x => ListaSucursalesPermitidas.Contains(x.id)).OrderByDescending(y => y.id), "id", "nombre_sucursal");
            return View();
        }

        public PartialViewResult HistorialCreditosVistaParcial(int id_sucursal, bool solamente_pendientes)
        {
            List<venta> ListaVentasCreditoCliente = new List<venta>();
            if (solamente_pendientes)
            {
                ListaVentasCreditoCliente = db.venta.Where(x => x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && x.aduedo.Value != 0 && x.sucursal_id == id_sucursal && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
            }
            else
            {
                ListaVentasCreditoCliente = db.venta.Where(x => x.multiple_pago.Where(y => y.id_tipo_pago_venta == 4).Count() > 0 && x.sucursal_id == id_sucursal && (x.catalogo_status_id == 1 || x.catalogo_status_id == 9 || x.catalogo_status_id == 10 || x.catalogo_status_id == 11)).ToList();
            }
            ViewBag.ListaVentasCreditoCliente = ListaVentasCreditoCliente;
            return PartialView();
        }

        public PartialViewResult VistaParcialHistorialAbonosXCliente(int id_cliente)
        {

POS/Views/Credito/AbonoVentaCliente.cshtml
@model POS.Models.venta
@{
    ViewBag.Title = "POS - Abonar A Credito";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Abonar A Venta: @Model.Serie-@POS.Fn.Numeros.agregarCeros(Model.Folio.Value)</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        @using (Html.BeginForm("AplicarAbono", "Credito", FormMethod.Post, new { @id = "FormularioAbonoVenta", @style = "margin-bottom:0px;" }))
        { 
            <table id="TablaAbonoVentaCredito" class="table" style="width: 100%;">
                <tbody>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Id Cliente: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.id" readonly="readonly" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Cliente: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.cliente.Razon_social" readonly="readonly" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Id Venta: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.Serie-@POS.Fn.Numeros.agregarCeros(Model.Folio.Value)" readonly="readonly" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Fecha De Entrega: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.Fecha_entrega" readonly="readonly" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Sucursal: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.sucursal.nombre_sucursal" readonly="readonly" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Vendedor: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.usuario_punto_venta.nombre_usuario" readonly="readonly" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Total: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" id="adeudo_total" class="form-control" value="@Model.total" readonly="readonly" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Adeudo: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" id="adeudo_restante" class="form-control" value="@Model.aduedo" readonly="readonly" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Abono: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" id="abono" class="form-control" name="abono" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Tipo De Pago: </td>
                        <td style="width: 25%; border: 0px;">
                            <select id="tipoPagoAbono" class="form-control" name="tipoPagoAbono"></select></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <div id="AlertaFormulario" class="alert alert-info" style="margin-bottom: 0px; width: 50%; display: none;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Por favor rellene todos los campos.</p>
                                </div>
                            </div>
                            <div id="AlertaCantidad" class="alert alert-info" style="margin-bottom: 0px; width: 50%; display: none;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>La cantidad a abonar es mayor a el aduedo.</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <a id="BotonAgregarAbonoVenta" class="btn btn-success">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-check"></i>
                                </span>
                                <span class="button-content">Agregar</span>
                            </a>
                            <a href="@Url.Action("MostrarCreditosClientes", new { id = Model.Cliente_id })" class="btn btn-danger">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-times"></i>
                                </span>
                                <span class="button-content">Cancelar</span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <input type="text" name="id" value="@Model.id" style="display:none" />
            <input type="submit" id="AgregarAbonoVenta" style="display: none;" />
        }
    </div>
</div>

<script>
    $(function () {
        var url = '@Url.Action("traerTipoPagoCredito")';
        $.ajax({
            type: "POST",
            url: url,
            data: {}
        }).done(function (x) {
            $('#tipoPagoAbono').append(x);
        });
    });
    $(document).on('click', '#BotonAgregarAbonoVenta', function () {
        var adeudo_total = parseFloat($('#adeudo_total').val());
        var adeudo_restante = parseFloat($('#adeudo_restante').val());
        var abono = parseFloat($('#abono').val());
        var restante = adeudo_restante - abono;
        if (restante >= 0)
        {
            $('#AgregarAbonoVenta').trigger('click');
        }
        else {
            MostrarAlertaCantidad();
            OcultarAlertaCantidad();
        }
    });
</script>

<script type="text/javascript">
    var seguir = true;
    $(document).ready(function () {
        $('#FormularioAbonoVenta').bind('submit', function (event) {
            seguir = true;
            $('.form-control').each(function () {
                if ($(this).val() == "") {
                    seguir = false;
                }
            });
            if (!seguir) {
                MostrarAlertaFormulario();
                OcultarAlertaFormulario();
            }
            if (!seguir) {
                return false;
            }
        });
    });
    function MostrarAlertaFormulario() {
        $('#AlertaFormulario').css('display', 'block').removeClass().addClass('bounceIn animated alert alert-info').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend');
    }
    function OcultarAlertaFormulario() {
        setTimeout(function () {
            $('#AlertaFormulario').removeClass().addClass('bounceOut animated alert alert-info').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend');
            $('#AlertaFormulario').hide(1500);
        }, 3000);
    }
    function MostrarAlertaCantidad() {
        $('#AlertaCantidad').css('display', 'block').removeClass().addClass('bounceIn animated alert alert-info').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend');
    }
    function OcultarAlertaCantidad() {
        setTimeout(function () {
            $('#AlertaCantidad').removeClass().addClass('bounceOut animated alert alert-info').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend');
            $('#AlertaCantidad').hide(1500);
        }, 3000);
    }
</script>

POS/Views/Credito/EditarDiasCredito.cshtml
@model POS.Models.cliente
@{
    ViewBag.Title = "POS - Editar Dias De Credito";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Editar Dias De Credito</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        @using (Html.BeginForm("EditarDiasCredito", "Credito", FormMethod.Post, new { @style = "margin-bottom:0px;" }))
        { 
            <input name="id" value="@ViewBag.id" style="display:none;" />
            <table id="TablaUsuarios" class="table" style="width: 100%;">
                <tbody>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Cliente: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" value="@Model.Razon_social" readonly="readonly" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Dias de Credito: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" name="dias" value="@Model.dias_credito" /></td>
                        <td style=" border: 0px;"></td>
                        <td style=" border: 0px;"></td>
                    </tr>
                    <tr>
                        <td colspan="6" style=" border: 0px;">
                            <a id="BotonEditarCliente" class="btn btn-success">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-check"></i>
                                </span>
                                <span class="button-content">Agregar</span>
                            </a>
                            @if (Convert.ToInt32(ViewBag.ruta) == 1)
                            {
                                <a href="@Url.Action("Index")" class="btn btn-danger">
                                    <span class="glyph-icon icon-separator">
                                        <i class="glyph-icon icon-times"></i>
                                    </span>
                                    <span class="button-content">Cancelar</span>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("MostrarCreditosClientes", new { id = Model.id })" class="btn btn-danger">
                                    <span class="glyph-icon icon-separator">
                                        <i class="glyph-icon icon-times"></i>
                                    </span>
                                    <span class="button-content">Cancelar</span>
                                </a>
                            }
                        </td>
                    </tr>
                </tbody>
            </table>
            <input type="text" name="ruta" value="@ViewBag.ruta" style="display: none;" />
            <input type="submit" id="EditarCliente" value="Guardar" style="display: none;" />
        }
    </div>
</div>

<script type="text/javascript">
    $(document).on('click', '#BotonEditarCliente', function () {
        $('#EditarCliente').trigger('click');
    });
</script>

POS/Views/Credito/HistorialAbonosClientes.cshtml
@model IEnumerable<POS.Models.abono>
@{
    ViewBag.Title = "POS - Abonos";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Abonos</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        <div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a id="ExportarExcel" class="btn btn-success" style="margin-top: 6px;">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-excel-o"></i>
                </span>
                <span class="button-content">Exportar A Excel</span>
            </a>
        </div>
        <div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a id="ExportarPDF" class="btn btn-danger" style="margin-top: 6px;">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-pdf-o"></i>
                </span>
                <span class="button-content">Exportar A PDF</span>
            </a>
        </div>
        <div style="float: left; margin-bottom: 10px;">
            <div style="float: left; margin-left: 10px; margin-top: 10px;">
                <label>Sucursal: </label>
                @Html.DropDownList("id_sucursal", null, new { @class = "form-control", @style = "display: inline; width: 200px;" })
            </div>
        </div>
        <table id="TablaAbonos" class="table table-hover" style="width: 100%;">
            <thead>
                <tr>
                    <th>Sucursal</th>
                    <th>Id Abono</th>
                    <th>Id Venta</th>
                    <th>Cliente</th>
                    <th>Tipo De Pago</th>
                    <th>Fecha</th>
                    <th>Usuario Recibe</th>
                    <th>Estatus</th>
                    <th>Fecha De Cancelacion</th>
                    <th>Usuario Cancelacion</th>
                    <th>Importe</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody id="CuerpoTabla" style="font-size: 13px;"></tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        actualizar_vistas_parciales();
        $("#ExportarExcel").click(function () {
            $('#TablaAbonos .xlsx').trigger("click");
        });
    });
    $(document).on('change', '#id_sucursal', function () {
        establecer_id_sucursal_virtual(parseInt($(this).val()));
        var url = '@Url.Action("VistaParcialHistorialAbonosClientes")';
        $.ajax({
            url: url,
            data: { id_sucursal: $('#id_sucursal').val() },
            success: function (parcial) {
                $('#TablaAbonos').dataTable().fnClearTable();
                $('#TablaAbonos').dataTable().fnDestroy();
                actualizar_vistas_parciales();
            },
            async: false
        });
    });
    function CancelarAbono(id_abono) {
        var url = '@Url.Action("CancelaAbono")';
        $.ajax({
            url: url,
            data: { id: id_abono },
            success: function (result) {
                if (result.success) {
                    $('#TablaAbonos').dataTable().fnClearTable();
                    $('#TablaAbonos').dataTable().fnDestroy();
                    actualizar_vistas_parciales();
                }
                else {
                    alert("Ocurrion un error al intentar cancelar el abono");
                }
            },
            async: false
        });
    }
    function actualizar_vistas_parciales()
    {
        var id_sucursal_virtual = recuperar_id_sucursal_virtual();
        if (id_sucursal_virtual != null)
            _id_sucursal = id_sucursal_virtual;
        else
            _id_sucursal = $("#id_sucursal").val();
        var url = '@Url.Action("VistaParcialHistorialAbonosClientes")';
        $.ajax({
            url: url,
            data: { id_sucursal: _id_sucursal },
            success: function (parcial) {
                $("#CuerpoTabla").html(parcial);
                $(".wrapper-dropdown-5").each(function () {
                    var dd = new DropDown($(this));
                    $(document).click(function () {
                        // all dropdowns
                        $('.wrapper-dropdown-5').removeClass('active');
                    });
                });
                CrearTablaAbonos();
            },
            async: false
        });
    }
    function DropDown(el) {
        this.dd = el;
        this.initEvents();
    }
    DropDown.prototype = {
        initEvents: function () {
            var obj = this;
            obj.dd.on('click', function (event) {
                $(this).toggleClass('active');
                event.stopPropagation();
            });
        }
    }
</script>

<script type="text/javascript">
    function CrearTablaAbonos() {
        $('#TablaAbonos').dataTable({
            "pagingType": "full_numbers",
            stateSave: true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "retrieve": true,
            "destroy": true,
            "autoWidth": true,
            dom: 'Bflrtip',
            buttons: [
                {
                    extend: 'copyHtml5',
                    text: '<i class="glyph-icon icon-clipboard"></i></span><span class="button-content">&nbsp;&nbsp;Copiar',
                    titleAttr: 'Copiar al Portapapeles',
                    className: 'btn btn-default',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                    }
                },
                {
                    extend: 'excelHtml5',
                    title: 'Lista de Creditos por Venta',
                    text: '<i class="glyph-icon icon-file-excel-o"></i></span><span class="button-content">&nbsp;&nbsp;Excel',
                    titleAttr: 'Exporta a Excel',
                    className: 'btn btn-success',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                    }
                },
                {
                    extend: 'pdfHtml5',
                    title: 'Lista de Creditos por Venta',
                    text: '<i class="glyph-icon icon-file-pdf-o"></i></span><span class="button-content">&nbsp;&nbsp;PDF',
                    titleAttr: 'Exporta a PDF',
                    className: 'btn btn-danger',
                    message: 'Creditos por Venta',
                    orientation: 'landscape',
                    pageSize: 'LETTER',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
                    }
                }
            ],
            language: idioma_espaniol_datatable
        });
    }
    $('#ExportarPDF').click(function () {
        descargar_pdf();
    });
    function descargar_pdf() {
        var id_sucursal = $("#id_sucursal").val();
        var url = '@Url.Action("TraerPDFListaAbonosClientes", "FormatoPDF", new { id_sucursal = "_id_" })'.replace("_id_", id_sucursal);
        url = url.replace(/amp;/g, "");
        window.open(url);
    }
</script>