POS/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Models;
using POS.Fn;
using System.Web.Security;

namespace POS.Controllers
{
    public class UsuarioController : Controller
    {
        private moragas_pruebasEntities1 db = new moragas_pruebasEntities1();

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Lista De Usuarios")]
        public ViewResult Index()
        {
            List<int> ListaSucursalesPermitidas = Fn.usuario_logeado.Sucursales_id();
            ViewBag.id_sucursal = new SelectList(db.sucursal.Where(x => ListaSucursalesPermitidas.Contains(x.id)).OrderByDescending(y => y.id), "id", "nombre_sucursal");
            return View();
        }

        public PartialViewResult VistaParcialUsuario(int id_sucursal)
        {
            // nivel usuario
            // 1 - Quianty
            // 2 - Admin    
            // 3 - Usuario
            int nivelUsuario = Fn.usuario_logeado.nivel_id();
            if (nivelUsuario == 1 || nivelUsuario == 2)
            {
                List<usuario_punto_venta> ListaUsuarios = db.usuario_punto_venta.Where(x => x.nivel_usuario_id >= nivelUsuario && x.sucursales_por_usuario.Select(y => y.sucursal_id).ToList().Contains(id_sucursal)).ToList();
                ViewBag.ListaUsuarios = ListaUsuarios;
            }
            else if (nivelUsuario == 3)
            {
                int id_usuario_logeado = Fn.usuario_logeado.traerUsuario().id;
                List<usuario_punto_venta> ListaUsuarios = db.usuario_punto_venta.Where(x => x.id == id_usuario_logeado).ToList();
                ViewBag.ListaUsuarios = ListaUsuarios;
            }
            return PartialView();
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Crear Usuario")]
        public ActionResult NuevoUsuario()
        {
            usuario_punto_venta usuario_logeado = Fn.usuario_logeado.traerUsuario();
            List<int> ListaPermisosUsuarioLogeado = usuario_logeado.permiso_vista_por_usuario.Select(x => x.permiso_vista_id).ToList();
            int id_nivel_usuario = Fn.usuario_logeado.nivel_id();
            List<int> ListaSucursalesPermitidas = Fn.usuario_logeado.Sucursales_id();
            List<sucursal> ListaSucursales = db.sucursal.Where(x => ListaSucursalesPermitidas.Contains(x.id)).ToList();
            List<permiso_vista> ListaPermisos = db.permiso_vista.Where(x => ListaPermisosUsuarioLogeado.Contains(x.id)).ToList();
            List<usuario_punto_venta> ListaUsuarios = db.usuario_punto_venta.Where(x => x.nivel_usuario_id >= id_nivel_usuario).ToList();
            List<int> ListaUsuariosConPermiso = new List<int>();
            foreach (usuario_punto_venta usuario in ListaUsuarios)
            {
                List<int> ListaSucursalesPorUsuarios = usuario.sucursales_por_usuario.Select(x => x.sucursal_id.Value).ToList();
                if (ListaSucursalesPermitidas.Except(ListaSucursalesPorUsuarios).Count() != ListaSucursalesPermitidas.Count)
                    ListaUsuariosConPermiso.Add(usuario.id);
            }
            ViewBag.ListaSucursales = ListaSucursales;
            ViewBag.ListaPermisos = ListaPermisos;
            ViewBag.id_usuario_seleccionado = new SelectList(db.usuario_punto_venta.Where(x => ListaUsuariosConPermiso.Contains(x.id)), "id", "nombre_usuario");
            ViewBag.nivel_usuario_id = new SelectList(db.nivel_usuario.Where(x => x.id >= id_nivel_usuario), "id", "nombre");
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult NuevoUsuario(usuario_punto_venta usuario, string[] sucursalesSeleccionadas, string[] permisosSeleccionados)
        {
            usuario.usuario_facturacion_id = 0;
            db.usuario_punto_venta.Add(usuario);
            db.SaveChanges();
            //ACTUALIZAR SUCURSALES POR USUARIO
            actualizaSucursalesUsuario(sucursalesSeleccionadas, usuario);
            actualizaPermisosUsuario(permisosSeleccionados, usuario);
            return RedirectToAction("Index");
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Editar Usuario")]
        public ActionResult EditarUsuario(int id)
        {
            // nivel usuario
            // 1 - Quianty
            // 2 - Admin    
            // 3 - Usuario
            usuario_punto_venta usuario = db.usuario_punto_venta.Find(id);
            List<int> ListaPermisosUsuarioEditar = usuario.permiso_vista_por_usuario.Select(x => x.permiso_vista_id).ToList();
            List<int> ListaSucursalesUsuarioEditar = usuario.sucursales_por_usuario.Select(x => x.sucursal_id.Value).ToList();
            int id_nivel_usuario = Fn.usuario_logeado.nivel_id();
            if (id_nivel_usuario <= usuario.nivel_usuario_id)
            {
                usuario_punto_venta usuario_logeado = Fn.usuario_logeado.traerUsuario();
                List<int> ListaPermisosUsuarioLogeado = usuario_logeado.permiso_vista_por_usuario.Select(x => x.permiso_vista_id).ToList();
                List<permiso_vista> ListaPermisos = db.permiso_vista.Where(x => ListaPermisosUsuarioLogeado.Contains(x.id)).ToList();
                List<int> ListaIdsPermisos = ListaPermisos.Select(x => x.id).ToList();
                List<int> ListaIdsPermisosActuales = ListaPermisosUsuarioEditar.Except(ListaIdsPermisos).ToList();
                List<permiso_vista> ListaPermisosActuales = db.permiso_vista.Where(x => ListaIdsPermisosActuales.Contains(x.id)).ToList();
                List<int> ListaSucursalesUsuarioLogeado = usuario_logeado.sucursales_por_usuario.Select(x => x.sucursal_id.Value).ToList();
                List<sucursal> ListaSucursales = db.sucursal.Where(x => ListaSucursalesUsuarioLogeado.Contains(x.id)).ToList();
                List<int> ListaIdsSucursales = ListaSucursales.Select(x => x.id).ToList();
                List<int> ListaIdsSucursalesActuales = ListaSucursalesUsuarioEditar.Except(ListaIdsSucursales).ToList();
                List<sucursal> ListaSucursalesActuales = db.sucursal.Where(x => ListaIdsSucursalesActuales.Contains(x.id)).ToList();
                List<int> ListaSucursalesPermitidas = Fn.usuario_logeado.Sucursales_id();
                List<usuario_punto_venta> ListaUsuarios = db.usuario_punto_venta.Where(x => x.nivel_usuario_id >= id_nivel_usuario).ToList();
                List<int> ListaUsuariosConPermiso = new List<int>();
                foreach (usuario_punto_venta usuario_aux in ListaUsuarios)
                {
                    List<int> ListaSucursalesPorUsuarios = usuario_aux.sucursales_por_usuario.Select(x => x.sucursal_id.Value).ToList();
                    if (ListaSucursalesPermitidas.Except(ListaSucursalesPorUsuarios).Count() != ListaSucursalesPermitidas.Count)
                        ListaUsuariosConPermiso.Add(usuario_aux.id);
                }
                ViewBag.ListaSucursalesActuales = ListaSucursalesActuales;
                ViewBag.ListaSucursales = ListaSucursales;
                ViewBag.ListaPermisosActuales = ListaPermisosActuales;
                ViewBag.ListaPermisos = ListaPermisos;
                ViewBag.id_usuario_seleccionado = new SelectList(db.usuario_punto_venta.Where(x => ListaUsuariosConPermiso.Contains(x.id)), "id", "nombre_usuario", usuario.id);
                ViewBag.nivel_usuario_id = new SelectList(db.nivel_usuario.Where(x => x.id >= id_nivel_usuario), "id", "nombre", usuario.nivel_usuario_id);
                ViewBag.id_estatus_usuario = new SelectList(db.estatus_usuario, "id", "nombre", usuario.id_estatus_usuario);
                return View(usuario);
            }
            else
            {
                return RedirectToAction("AccesoDenegadoNivel", "Account");
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult EditarUsuario(usuario_punto_venta usuario, string[] sucursalesSeleccionadas, string[] permisosSeleccionados)
        {
            db.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            //ACTUALIZAR SUCURSALES POR USUARIO
            actualizaSucursalesUsuario(sucursalesSeleccionadas, usuario);
            actualizaPermisosUsuario(permisosSeleccionados, usuario);
            return RedirectToAction("Index");
        }

        public PartialViewResult ModalAdvertenciaUsuario()
        {
            return PartialView();
        }

        private void actualizaPermisosUsuario(string[] permisosSeleccionados, usuario_punto_venta usuarioActualizar)
        {
            //   E L I M I N A   T O D A S   S U C U R S A L E S 
            //**************************************************//
            List<permiso_vista_por_usuario> eliminarPermisosUsuario = db.permiso_vista_por_usuario.Where(x => x.usuario_punto_venta_id == usuarioActualizar.id).ToList();
            if (eliminarPermisosUsuario.Count() != 0)
            {
                foreach (var permisoEliminar in eliminarPermisosUsuario)
                {
                    db.permiso_vista_por_usuario.Remove(permisoEliminar);
                }
            }
            //   A G R E G A    S U C U R S A L E S 
            //***************************************//
            if (permisosSeleccionados != null)
            {
                //POR CADA ID EN LA LISTA 'sucursalesSeleccionadas'
                foreach (var idPermisoAgregar in permisosSeleccionados)
                {
                    permiso_vista_por_usuario pu = new permiso_vista_por_usuario();
                    pu.permiso_vista_id = Convert.ToInt16(idPermisoAgregar);
                    pu.usuario_punto_venta_id = usuarioActualizar.id;
                    db.permiso_vista_por_usuario.Add(pu);
                }
            }
            db.SaveChanges();
        }

POS/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "POS - Usuarios";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Usuarios</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        <div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a href="@Url.Action("NuevoUsuario")" class="btn btn-success">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-plus"></i>
                </span>
                <span class="button-content">Nuevo Usuario</span>
            </a>
        </div>
        @*<div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a id="ExportarExcel" class="btn btn-success">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-excel-o"></i>
                </span>
                <span class="button-content">Exportar A Excel</span>
            </a>
        </div>
        <div style="margin-right: 10px; margin-top: 4px; float: right;">
            <a id="ExportarPDF" class="btn btn-danger" style="margin-top: 6px;">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-pdf-o"></i>
                </span>
                <span class="button-content">Exportar A PDF</span>
            </a>
        </div>*@
        <div style="float: left; margin-bottom: 10px;">
            <div style="float: left; margin-left: 10px; margin-top: 10px;">
                <label>Sucursal: </label>
                @Html.DropDownList("id_sucursal", null, new { @class = "form-control", @style = "display: inline; width: 200px;" })
            </div>
        </div>
        <table id="TablaUsuarios" class="table table-hover" style="width: 100%;">
            <thead>
                <tr>
                    <th>Nivel De Usuario</th>
                    <th>Nombre</th>
                    <th>Contraseña</th>
                    <th>Sucursales</th>
                    <th>Estatus</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody id="CuerpoTabla">
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        ActualizarVistaParcial();
        $("#ExportarExcel").click(function () {
            $('#TablaUsuarios .xlsx').trigger("click");
        });
    });
    $(document).on('change', '#id_sucursal', function () {
        establecer_id_sucursal_virtual(parseInt($(this).val()));
        ActualizarVistaParcial();
    });
    function EditarUsuario(id) {
        window.location.href = '@Url.Action("EditarUsuario", new { id = "_id_" })'.replace("_id_", id);
    }
    function DropDown(el) {
        this.dd = el;
        this.initEvents();
    }
    DropDown.prototype = {
        initEvents: function () {
            var obj = this;
            obj.dd.on('click', function (event) {
                $(this).toggleClass('active');
                event.stopPropagation();
            });
        }
    }
    function ActualizarVistaParcial()
    {
        var id_sucursal_virtual = recuperar_id_sucursal_virtual();
        if (id_sucursal_virtual != null)
            _id_sucursal = id_sucursal_virtual;
        else
            _id_sucursal = $("#id_sucursal").val();
        var url = '@Url.Action("VistaParcialUsuario")';
        $.ajax({
            url: url,
            data: { id_sucursal: _id_sucursal },
            success: function (parcial) {
                $("#CuerpoTabla").html(parcial);
                $(".wrapper-dropdown-5").each(function () {
                    var dd = new DropDown($(this));
                    $(document).click(function () {
                        // all dropdowns
                        $('.wrapper-dropdown-5').removeClass('active');
                    });
                });
                CrearTablaUsuarios();
            },
            async: false
        });
    }
    $('#ExportarPDF').click(function () {
        descargar_pdf();
    });
    function descargar_pdf() {
        var id_sucursal = $("#id_sucursal").val();
        var id_usuario = @POS.Fn.usuario_logeado.traerUsuario().id;
        var url = '@Url.Action("TraerPDFListaUsuarios", "FormatoPDF", new { id_sucursal = "_id_", id_usuario = "_id_usuario_" })'.replace("_id_", id_sucursal);
        url = url.replace("_id_usuario_", id_usuario);
        url = url.replace(/amp;/g, "");
        window.open(url);
    }
</script>

<script type="text/javascript">
    function CrearTablaUsuarios() {
        $('#TablaUsuarios').dataTable({
            "pagingType": "full_numbers",
            stateSave: true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "retrieve": true,
            "destroy": true,
            "autoWidth": true,
            dom: 'Bflrtip',
            buttons: [
                {
                    extend: 'copyHtml5',
                    text: '<i class="glyph-icon icon-clipboard"></i></span><span class="button-content">&nbsp;&nbsp;Copiar',
                    titleAttr: 'Copiar al Portapapeles',
                    className: 'btn btn-default',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                {
                    extend: 'excelHtml5',
                    title: 'Lista de Usuarios',
                    text: '<i class="glyph-icon icon-file-excel-o"></i></span><span class="button-content">&nbsp;&nbsp;Excel',
                    titleAttr: 'Exporta a Excel',
                    className: 'btn btn-success',

                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                {
                    extend: 'pdfHtml5',
                    title: 'Lista de Usuarios',
                    text: '<i class="glyph-icon icon-file-pdf-o"></i></span><span class="button-content">&nbsp;&nbsp;PDF',
                    titleAttr: 'Exporta a PDF',
                    className: 'btn btn-danger',

                    message: 'Usuarios',
                    orientation: 'landscape',
                    pageSize: 'LETTER',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                }
            ],
            language: idioma_espaniol_datatable
        });
    }
</script>

POS/Views/Usuario/NuevoUsuario.cshtml
@model POS.Models.usuario_punto_venta
@{
    ViewBag.Title = "POS - Nuevo Usuario";
    List<POS.Models.sucursal> ListaSucursales = ViewBag.ListaSucursales as List<POS.Models.sucursal>;
    List<POS.Models.permiso_vista> ListaPermisos = ViewBag.ListaPermisos as List<POS.Models.permiso_vista>;
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Nuevo Usuario</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        @using (Html.BeginForm("NuevoUsuario", "Usuario", FormMethod.Post, new { @id = "NuevoUsuario", @style = "margin-bottom:0px;" }))
        { 
            @Html.AntiForgeryToken()
            <table id="TablaUsuarios" class="table" style="width: 100%;">
                <tbody>
                    <tr>
                        <td colspan="6" style="border: 0px; text-align: center; background-color: #506676; color: white;">Informacion General</td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Nombre De Usuario: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" id="nombre_usuario" name="nombre_usuario" /></td>
                        <td style="width: 150px; text-align: right; border: 0px;">Contraseña: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="password" class="form-control" id="pw" name="pw" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Nivel De Usuario: </td>
                        <td style="width: 25%; border: 0px;">@Html.DropDownList("nivel_usuario_id", null, new { @class = "form-control" })</td>
                        <td style="width: 150px; text-align: right; border: 0px;">Activo: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" id="id_estatus_usuario" name="id_estatus_usuario" value="1" style="display: none;" />
                            <input type="checkbox" class="switch-sucursal" style="margin: 5px" id="check_estatus_usuario" value="true" checked="checked" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px; text-align: center; background-color: #506676; color: white;">Sucursales</td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <table class="table" style="width: 100%;">
                                <tr>
                                    <td colspan="7" style="border: 0px;">
                                        @foreach (POS.Models.sucursal sucursal in ListaSucursales)
                                        {
                                            <input type="checkbox" class="switch-sucursal" style="margin:5px" name="sucursalesSeleccionadas" value="@sucursal.id" @(false ? "checked=\"checked\"" : "")) /><label style="margin: 0px  20px 0 5px; font-weight: normal">@sucursal.nombre_sucursal</label>
                                        }
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px; text-align: center; background-color: #506676; color: white;">Permisos</td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <table id="tablePermisos">
                                <thead>
                                    <tr>
                                        <td colspan="6">
                                            @Html.DropDownList("id_usuario_seleccionado", null, new { @class = "form-control", @style = "width: 200px; display:inline;" })
                                            <a id="btn_copiar_permisos" class="btn btn-info">
                                                <span class="glyph-icon icon-separator">
                                                    <i class="glyph-icon icon-check"></i>
                                                </span>
                                                <span class="button-content">Copiar Permisos</span>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="height: 20px;"></td>
                                    </tr>
                                </thead>
                                <tbody>
                                        @foreach (var permisosControlador in ListaPermisos.GroupBy(x => x.nombreControlador))
                                        {
                                            <tr>
                                                <td>@permisosControlador.First().nombreControlador.ToUpper()</td>
                                            </tr>
                                            <tr>
                                                @foreach (var permisoVista in permisosControlador)
                                            {
                                                <td>
                                                    <div style="display: inline">
                                                        <input type="checkbox" class="switch-sucursal" style="margin:5px" name="permisosSeleccionados" value="@permisoVista.id" @(false ? "checked=\"checked\"" : "")) />
                                                    </div>
                                                    <label style="margin: 0 20px 0 5px; font-weight: normal">@permisoVista.nombreVistaPublico</label>
                                                </td>
                                            }
                                        </tr>
                                        <tr>
                                            <td style="height: 20px;"></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <div id="AlertaFormulario" class="alert alert-info" style="margin-bottom: 0px; width: 50%; display: none;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Por favor rellene todos los campos.</p>
                                </div>
                            </div>
                            <div id="AlertaUsuario" class="alert alert-info" style="display: none; margin-bottom: 0px; width: 50%; margin-top: 10px;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Nombre de usuario ya registrado en el sistema.</p>
                                </div>
                            </div>
                            <div id="AlertaPassword" class="alert alert-info" style="display: none; margin-bottom: 0px; width: 50%; margin-top: 10px;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Verifique su contraseña. Mínimo 8 caracteres. Debe contener Mayúsculas, minúsculas y números. Se recomienda incluir algún carácter especial.</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <a id="BotonAgregarUsuario" class="btn btn-success">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-check"></i>
                                </span>
                                <span class="button-content">Agregar</span>
                            </a>
                            <a href="@Url.Action("Index")" class="btn btn-danger">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-times"></i>
                                </span>
                                <span class="button-content">Cancelar</span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <input type="submit" id="AgregarUsuario" value="Guardar" style="display: none;" />
        }
    </div>
</div>

<script type="text/javascript">
    $(document).on('click', '#BotonAgregarUsuario', function () {
        $('#AgregarUsuario').trigger('click');
    });
</script>

<script type="text/javascript">
    var seguir = true;
    var contraseniaSegura = true;
    $(document).ready(function () {
        var elems = Array.prototype.slice.call(document.querySelectorAll('.switch-sucursal'));
        elems.forEach(function (html) {
            var switchery = new Switchery(html, { size: 'small', secondaryColor: 'rgb(206, 199, 199)' });
        });
        $('#NuevoUsuario').bind('submit', function (event) {
            seguir = true;
            $('.form-control').each(function () {
                if ($(this).val() == "") {
                    seguir = false;
                }
            });
            if (!seguir) {
                $("#AlertaFormulario").slideDown('slow').delay(3000).slideUp('slow');
            }
            //VerificarContrasena();
            VerificarUsuario();
            if (!seguir) {
                return false;
            }
        });
    });
    $(document).on('change', '#check_estatus_usuario', function () {
        if ($('#check_estatus_usuario').is(':checked')) {
            $('#id_estatus_usuario').val("1");
        } else {
            $('#id_estatus_usuario').val("2");
        }
    });
    $(document).on('change', '#pw', function () {
       // VerificarContrasena();
    });
    $(document).on('change', '#nombre_usuario', function () {
        VerificarUsuario();
    });
    function VerificarUsuario() {
        var url = '@Url.Action("VerificarUsuario")';
        $.ajax({
            url: url,
            data: { id: 0, usuario: $('#nombre_usuario').val() },
            type: "POST",
            async: false,
            success: function (existe) {
                if (existe == "True") {
                    $("#AlertaUsuario").slideDown('slow').delay(3000).slideUp('slow');
                    seguir = false;
                }
            }
        });
    }
    function VerificarContrasena() {
        contraseniaSegura = true;
        var pswd = $('#pw').val();
        if (pswd.length < 8) {
            contraseniaSegura = false;
        }
        else if (!(pswd.match(/[A-z]/))) {
            contraseniaSegura = false;
        }
        else if (!(pswd.match(/[A-Z]/))) {
            contraseniaSegura = false;
        }
        else if (!(pswd.match(/\d/))) {
            contraseniaSegura = false;
        }
        if (!contraseniaSegura) {
            $("#AlertaPassword").slideDown('slow').delay(3000).slideUp('slow');
            seguir = false;
        }
    }
    $(document).on('click', '#btn_copiar_permisos', function () {
        $("#tablePermisos tbody").html("<tr><td>....CargandoPermisos</td></tr>");
        var url = '@Url.Action("parcial_traerPermisosUsuario")';
        _id = parseInt($("#id_usuario_seleccionado option:selected").val());
        $.ajax({
            url: url,
            data: { id: $("#id_usuario_seleccionado option:selected").val() },
            success: function (permisos) {
                $("#tablePermisos tbody").hide().html(permisos).fadeIn('slow');
                //    S W I T C H E R Y 
                var elems = Array.prototype.slice.call(document.querySelectorAll('.switch-permiso'));
                elems.forEach(function (html) {
                    var switchery = new Switchery(html, { size: 'small', secondaryColor: 'rgb(206, 199, 199)' });
                });
                //    S W I T C H E R Y 
            },
            async: false
        });
    });
</script>