POS/Controllers/TipoPrecioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Models;
using System.Data.Entity;
using POS.Fn;

namespace POS.Controllers
{
    public class TipoPrecioController : Controller
    {

        moragas_pruebasEntities1 db = new moragas_pruebasEntities1();

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Lista De Tipos De Precios")]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult VistaParcialTipoPrecio()
        {
            List<tipocliente> ListaClientes = db.tipocliente.OrderBy(x => x.orden).ToList();
            ViewBag.ListaClientes = ListaClientes;
            return PartialView();
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Crear Tipo De Precio")]
        public ActionResult NuevoTipoPrecio()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevoTipoPrecio(tipocliente tipo_precio)
        {
            db.tipocliente.Add(tipo_precio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Editar Tipo De Precio")]
        public ActionResult EditarTipoPrecio(int id)
        {
            tipocliente tipo_precio = db.tipocliente.Find(id);
            return View(tipo_precio);
        }

        [HttpPost]
        public ActionResult EditarTipoPrecio(tipocliente tipo_precio)
        {
            db.Entry(tipo_precio).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public bool VerificarTipoPrecio(int id, String tipo_precio)
        {
            bool existe;
            if (id == 0)
                existe = db.tipocliente.Where(x => x.Tipo.ToLower().Equals(tipo_precio.ToLower())).Any();
            else
                existe = db.tipocliente.Where(x => x.id != id && x.Tipo.ToLower().Equals(tipo_precio.ToLower())).Any();
            return existe;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

POS/Views/TipoPrecio/EditarTipoPrecio.cshtml
@model POS.Models.tipocliente
@{
    ViewBag.Title = "POS - Editar Tipo De Precio";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Editar Tipo De Precio</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        @using (Html.BeginForm("EditarTipoPrecio", "TipoPrecio", FormMethod.Post, new { @id = "EditarTipoPrecio", @style = "margin-bottom:0px;" }))
        { 
            @Html.HiddenFor(model => model.id)
            <table id="TablaTiposPrecios" class="table" style="width: 100%;">
                <tbody>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Tipo De Precio: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" id="Tipo" name="Tipo" value="@Model.Tipo" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <div id="AlertaFormulario" class="alert alert-info" style="margin-bottom: 0px; width: 50%; display: none;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Por favor rellene todos los campos.</p>
                                </div>
                            </div>
                            <div id="AlertaTipoPrecio" class="alert alert-info" style="display: none; margin-bottom: 0px; width: 50%; margin-top: 10px;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Tipo de precio ya registrado en el sistema.</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <a id="BotonEditarTipoPrecio" class="btn btn-success">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-check"></i>
                                </span>
                                <span class="button-content">Guardar Cambios</span>
                            </a>
                            <a href="@Url.Action("Index")" class="btn btn-danger">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-times"></i>
                                </span>
                                <span class="button-content">Cancelar</span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <input type="submit" id="EditarTipoPrecio" value="Guardar" style="display: none;" />
        }
    </div>
</div>

<script type="text/javascript">
    $(document).on('click', '#BotonEditarTipoPrecio', function () {
        $('#EditarTipoPrecio').trigger('click');
    });
</script>

<script type="text/javascript">
    var seguir = true;
    $(document).ready(function () {
        $('#EditarTipoPrecio').bind('submit', function (event) {
            seguir = true;
            $('.form-control').each(function () {
                if ($(this).val() == "") {
                    seguir = false;
                }
            });
            if (!seguir) {
                $("#AlertaFormulario").slideDown('slow').delay(3000).slideUp('slow');
            }
            VerificarTipoPrecio();
            if (!seguir) {
                return false;
            }
        });
    });
    $(document).on('change', '#Tipo', function () {
        VerificarTipoPrecio();
    });
    function VerificarTipoPrecio() {
        var url = '@Url.Action("VerificarTipoPrecio")';
        $.ajax({
            url: url,
            data: { id: @Model.id, tipo_precio: $('#Tipo').val() },
                type: "POST",
                async: false,
                success: function (existe) {
                    if (existe == "True") {
                        $("#AlertaTipoPrecio").slideDown('slow').delay(3000).slideUp('slow');
                        seguir = false;
                    }
                }
            });
        }
</script>

POS/Views/TipoPrecio/Index.cshtml
@{
    ViewBag.Title = "POS - Tipos De Precio";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Tipos De Precio</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        <div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a href="@Url.Action("NuevoTipoPrecio")" class="btn btn-success" style="margin-top: 6px;">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-plus"></i>
                </span>
                <span class="button-content">Nuevo Tipo De Precio</span>
            </a>
        </div>
        @*<div style="margin-right: 10px; margin-top: 16px; float: right;">
            <a id="ExportarExcel" class="btn btn-success">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-excel-o"></i>
                </span>
                <span class="button-content">Exportar A Excel</span>
            </a>
        </div>
        <div style="margin-right: 10px; margin-top: 10px; float: right;">
            <a id="ExportarPDF" class="btn btn-danger" style="margin-top: 6px;">
                <span class="glyph-icon icon-separator">
                    <i class="glyph-icon icon-file-pdf-o"></i>
                </span>
                <span class="button-content">Exportar A PDF</span>
            </a>
        </div>*@
        <table id="TablaTiposPrecios" class="table table-hover" style="width: 100%;">
            <thead>
                <tr>
                    <th>Tipo De Precio</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody id="CuerpoTabla">
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready(function () {
        var url = '@Url.Action("VistaParcialTipoPrecio")';
        $.ajax({
            url: url,
            data: { },
            success: function (parcial) {
                $("#CuerpoTabla").html(parcial);
                $(".wrapper-dropdown-5").each(function () {
                    var dd = new DropDown($(this));
                    $(document).click(function () {
                        // all dropdowns
                        $('.wrapper-dropdown-5').removeClass('active');
                    });
                });
                CrearTablaTiposDePrecios();
            },
            async: false
        });
        $("#ExportarExcel").click(function () {
            $('#TablaTiposPrecios .xlsx').trigger("click");
        });
    });

    function EditarTipoPrecio(id) {
        window.location.href = '@Url.Action("EditarTipoPrecio", new { id = "_id_" })'.replace("_id_", id);
    }
    function DropDown(el) {
        this.dd = el;
        this.initEvents();
    }
    DropDown.prototype = {
        initEvents: function () {
            var obj = this;
            obj.dd.on('click', function (event) {
                $(this).toggleClass('active');
                event.stopPropagation();
            });
        }
    }
</script>

<script type="text/javascript">
    function CrearTablaTiposDePrecios() {
        $('#TablaTiposPrecios').dataTable({
            "pagingType": "full_numbers",
            stateSave: true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "retrieve": true,
            "destroy": true,
            "autoWidth": true,
            dom: 'Bflrtip',
            buttons: [
                {
                    extend: 'copyHtml5',
                    text: '<i class="glyph-icon icon-clipboard"></i></span><span class="button-content">&nbsp;&nbsp;Copiar',
                    titleAttr: 'Copiar al Portapapeles',
                    className: 'btn btn-default',
                    exportOptions: {
                        columns: [0]
                    }
                },
                {
                    extend: 'excelHtml5',
                    title: 'Lista de Tipos de Precio',
                    text: '<i class="glyph-icon icon-file-excel-o"></i></span><span class="button-content">&nbsp;&nbsp;Excel',
                    titleAttr: 'Exporta a Excel',
                    className: 'btn btn-success',
                    exportOptions: {
                        columns: [0]
                    }
                },
                {
                    extend: 'pdfHtml5',
                    title: 'Lista de Tipos de Precio',
                    text: '<i class="glyph-icon icon-file-pdf-o"></i></span><span class="button-content">&nbsp;&nbsp;PDF',
                    titleAttr: 'Exporta a PDF',
                    className: 'btn btn-danger',
                    message: 'Tipos de Precio',
                    orientation: 'landscape',
                    pageSize: 'LETTER',
                    exportOptions: {
                        columns: [0]
                    }
                }
            ],
            language: idioma_espaniol_datatable
        });
    }
    $('#ExportarPDF').click(function () {
        descargar_pdf();
    });
    function descargar_pdf() {
        var url = '@Url.Action("TraerPDFListaTiposPrecio", "FormatoPDF")';
        window.open(url);
    }
</script>

POS/Views/TipoPrecio/NuevoTipoPrecio.cshtml
@model POS.Models.tipocliente
@{
    ViewBag.Title = "POS - Nuevo Tipo De Precio";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Nuevo Tipo De Precio</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        @using (Html.BeginForm("NuevoTipoPrecio", "TipoPrecio", FormMethod.Post, new { @id = "NuevoTipoPrecio", @style = "margin-bottom:0px;" }))
        { 
            <table id="TablaTiposPrecios" class="table" style="width: 100%;">
                <tbody>
                    <tr>
                        <td style="width: 150px; text-align: right; border: 0px;">Tipo De Precio: </td>
                        <td style="width: 25%; border: 0px;">
                            <input type="text" class="form-control" id="Tipo" name="Tipo" /></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                        <td style="border: 0px;"></td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <div id="AlertaFormulario" class="alert alert-info" style="margin-bottom: 0px; width: 50%; display: none;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Por favor rellene todos los campos.</p>
                                </div>
                            </div>
                            <div id="AlertaTipoPrecio" class="alert alert-info" style="display: none; margin-bottom: 0px; width: 50%; margin-top: 10px;">
                                <div class="bg-red alert-icon"><i class="glyph-icon icon-times"></i></div>
                                <div class="alert-content">
                                    <h4 class="alert-title">Error</h4>
                                    <p>Tipo de precio ya registrado en el sistema.</p>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="border: 0px;">
                            <a id="BotonAgregarTipoPrecio" class="btn btn-success">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-check"></i>
                                </span>
                                <span class="button-content">Agregar</span>
                            </a>
                            <a href="@Url.Action("Index")" class="btn btn-danger">
                                <span class="glyph-icon icon-separator">
                                    <i class="glyph-icon icon-times"></i>
                                </span>
                                <span class="button-content">Cancelar</span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <input type="submit" id="AgregarTipoPrecio" value="Guardar" style="display: none;" />
        }
    </div>
</div>

<script type="text/javascript">
    $(document).on('click', '#BotonAgregarTipoPrecio', function () {
        $('#AgregarTipoPrecio').trigger('click');
    });
</script>

<script type="text/javascript">
    var seguir = true;
    $(document).ready(function () {
        $('#NuevoTipoPrecio').bind('submit', function (event) {
            seguir = true;
            $('.form-control').each(function () {
                if ($(this).val() == "") {
                    seguir = false;
                }
            });
            if (!seguir) {
                $("#AlertaFormulario").slideDown('slow').delay(3000).slideUp('slow');
            }
            VerificarTipoPrecio();
            if (!seguir) {
                return false;
            }
        });
    });
    $(document).on('change', '#Tipo', function () {
        VerificarTipoPrecio();
    });
    function VerificarTipoPrecio() {
        var url = '@Url.Action("VerificarTipoPrecio")';
        $.ajax({
            url: url,
            data: { id: 0, tipo_precio: $('#Tipo').val() },
            type: "POST",
            async: false,
            success: function (existe) {
                if (existe == "True") {
                    $("#AlertaTipoPrecio").slideDown('slow').delay(3000).slideUp('slow');
                    seguir = false;
                }
            }
        });
    }
</script>

POS/Views/TipoPrecio/VistaParcialTipoPrecio.cshtml
@{
    List<POS.Models.tipocliente> ListaClientes = ViewBag.ListaClientes as List<POS.Models.tipocliente>;
}


@foreach (POS.Models.tipocliente tipo_precio in ListaClientes)
{
    <tr>
        <td style="text-align: center;">@tipo_precio.Tipo</td>
        <td style="text-align: center;">
            @if (tipo_precio.id != 1)
            {
                <section>
                    <div class="wrapper-demo">
                        <div class="wrapper-dropdown-5" tabindex="1">
                            <i class="glyph-icon icon-bars" aria-hidden="true" style="margin-right: 12px;"></i>
                            Acciones
                            <ul class="dropdown" style="padding: 0px; text-align: left; margin-top: 0px;">
                                <li>
                                    <label onclick="EditarTipoPrecio(@tipo_precio.id)" style="color: #254054"><i class="glyph-icon icon-pencil" aria-hidden="true" style="margin-right: 15px;"></i>Editar</label>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
            }
        </td>
    </tr>
}

<script>
    $("#TablaTiposPrecios").tableExport({
        headings: true,                     // (Boolean), display table headings (th/td elements) in the <thead>
        footers: true,                      // (Boolean), display table footers (th/td elements) in the <tfoot>
        formats: ["xlsx", "csv", "txt"],     // (String[]), filetype(s) for the export
        fileName: "id",                     // (id, String), filename for the downloaded file
        bootstrap: true,                    // (Boolean), style buttons using bootstrap
        position: "bottom",                 // (top, bottom), position of the caption element relative to table
        ignoreRows: null,                   // (Number, Number[]), row indices to exclude from the exported file
        ignoreCols: 1,                   // (Number, Number[]), column indices to exclude from the exported file
        ignoreCSS: ".tableexport-ignore",   // (selector, selector[]), selector(s) to exclude cells from the exported file
        emptyCSS: ".tableexport-empty",     // (selector, selector[]), selector(s) to replace cells with an empty string in the exported file
        trimWhitespace: false               // (Boolean), remove all leading/trailing newlines, spaces (including non-breaking spaces), and tabs from cell text
    });
</script>