POS/Models/nota_credito.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_credito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nota_credito()
        {
            this.concepto_por_nota_credito = new HashSet<concepto_por_nota_credito>();
        }
    
        public int id { get; set; }
        public int id_venta { get; set; }
        public int id_estatus_nota_credito { get; set; }
        public int id_sucursal { get; set; }
        public int id_usuario_punto_venta { get; set; }
        public Nullable<int> id_venta_aplicada { get; set; }
        public Nullable<int> folio { get; set; }
        public string serie { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_uso { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concepto_por_nota_credito> concepto_por_nota_credito { get; set; }
        public virtual estatus_nota_credito estatus_nota_credito { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual usuario_punto_venta usuario_punto_venta { get; set; }
        public virtual venta venta { get; set; }
        public virtual venta venta1 { get; set; }
    }
}

POS/Controllers/NotaCreditoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POS.Models;
using System.Data.Entity;
using POS.Fn;
using System.Globalization;

namespace POS.Controllers
{
    public class NotaCreditoController : Controller
    {

        moragas_pruebasEntities1 db = new moragas_pruebasEntities1();
        CultureInfo IdiomaFecha = new CultureInfo("es-MX");

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName = "Historial De Notas De Credito")]
        public ActionResult Index()
        {
            ViewBag.HoyInicio = DateTime.Now.ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.HoyFin = DateTime.Now.ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.AyerInicio = DateTime.Now.AddDays(-1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.AyerFin = DateTime.Now.AddDays(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.AntierInicio = DateTime.Now.AddDays(-2).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.AntierFin = DateTime.Now.AddDays(-2).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.SemanaActualInicio = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.SemanaActualFin = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).AddDays(6).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.SemanaPasadaInicio = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).AddDays(-7).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.SemanaPasadaFin = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).AddDays(-7).AddDays(6).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.SemanaAntepasadaInicio = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).AddDays(-14).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.SemanaAntepasadaFin = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + 1).AddDays(-14).AddDays(6).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            DateTime hoy = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            int numero_de_dia = hoy.Day;
            if (numero_de_dia > 15)
            //segunda quincena
            {
                ViewBag.QuincenaActualInicio = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 15).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaActualFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.DaysInMonth(DateTime.Today.Year, DateTime.Today.Month)).ToString("MM/dd/yyyy") + " 11:59:59 PM";
                ViewBag.QuincenaPasadaInicio = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaPasadaFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddDays(15).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
                ViewBag.QuincenaAntepasadaInicio = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, 15).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaAntepasadaFin = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, DateTime.DaysInMonth(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month)).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            }
            else //primera quincena
            {
                ViewBag.QuincenaActualInicio = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaActualFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddDays(15).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
                ViewBag.QuincenaPasadaInicio = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, 15).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaPasadaFin = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, DateTime.DaysInMonth(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month)).ToString("MM/dd/yyyy") + " 11:59:59 PM";
                ViewBag.QuincenaAntepasadaInicio = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, 1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
                ViewBag.QuincenaAntepasadaFin = new DateTime(DateTime.Today.Year, DateTime.Today.AddMonths(-1).Month, 1).AddDays(15).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            }
            ViewBag.MesActualInicio = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.MesActualFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddMonths(1).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.MesPasadoInicioFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddMonths(-1).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.MesPasadoFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddMonths(-1).AddMonths(1).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.MesAntepasadoInicio = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddMonths(-2).ToString("MM/dd/yyyy") + " 12:00:00 AM";
            ViewBag.MesAntepasadoFin = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1).AddMonths(-2).AddMonths(1).AddSeconds(-1).ToString("MM/dd/yyyy") + " 11:59:59 PM";
            ViewBag.id_sucursal = new SelectList(db.sucursal.OrderByDescending(y => y.id), "id", "nombre_sucursal");
            ViewBag.id_estatus_nota_credito = new SelectList(db.estatus_nota_credito, "id", "nombre");
            return View();
        }

        public PartialViewResult VistaParcialNotaCredito(int id_sucursal, int id_estatus_nota_credito, String periodo)
        {
            List<nota_credito> ListaNotasCredito = db.nota_credito.ToList();
            if (id_sucursal != 0)
                ListaNotasCredito = ListaNotasCredito.Where(x => x.venta.sucursal_id == id_sucursal).ToList();
            if (id_estatus_nota_credito != 0)
                ListaNotasCredito = ListaNotasCredito.Where(x => x.id_estatus_nota_credito == id_estatus_nota_credito).ToList();
            if (!periodo.Equals(""))
            {
                String[] fecha = Fn.Fechas.CalcularIncioFin(periodo);
                String inicio = fecha[0];
                String fin = fecha[1];

                DateTime _inicio = Convert.ToDateTime(inicio, IdiomaFecha);
                DateTime _fin = Convert.ToDateTime(fin, IdiomaFecha);
                ListaNotasCredito = ListaNotasCredito.Where(x => x.fecha_creacion > _inicio && x.fecha_creacion < _fin).ToList();
            }
            return PartialView(ListaNotasCredito);
        }

        [Authorize]
        [AutorizacionVistaUsuarioActivo(displayName="Crear Nota De Credito")]
        public ActionResult NuevaNotaCredito()
        {
            return View();
        }

        public PartialViewResult VistaParcialNuevaNotaCredito(String id_venta)
        {
            try
            {
                String[] datos = id_venta.Split('-');
                String serie = datos[0];
                String folio_con_ceros = datos[1];
                String folio_sin_ceros = "";
                Boolean ignorar = false;
                for (int i = 0; i < 5; i++)
                {
                    if (!ignorar)
                    {
                        if (folio_con_ceros.ElementAt(i) != '0')
                        {
                            folio_sin_ceros = folio_sin_ceros + folio_con_ceros.ElementAt(i);
                            ignorar = true;
                        }
                    }
                    else
                        folio_sin_ceros = folio_sin_ceros + folio_con_ceros.ElementAt(i);
                }
                int folio = Convert.ToInt32(folio_sin_ceros);
                venta venta = db.venta.Where(x => x.Folio == folio && x.Serie.ToLower().Equals(serie.ToLower())).Single();
                if (venta.catalogo_status_id == 2 || venta.catalogo_status_id == 12)
                {
                    ViewBag.correcto = -1;
                    return PartialView();
                }
                else
                {
                    List<conceptos_por_venta> ListaConceptosVenta = venta.conceptos_por_venta.ToList();
                    List<nota_credito> ListaNotasCredito = venta.nota_credito.ToList();
                    List<int> ListaIdsNotasCredito = venta.nota_credito.Where(x => x.id_estatus_nota_credito != 3).Select(x => x.id).ToList();
                    List<concepto_por_nota_credito> ListaConceptosNotaCredito = db.concepto_por_nota_credito.Where(x => ListaIdsNotasCredito.Contains(x.id_nota_credito)).ToList();
                    foreach (conceptos_por_venta conceptos_por_venta in ListaConceptosVenta)
                    {
                        foreach (concepto_por_nota_credito concepto_por_nota_credito in ListaConceptosNotaCredito)
                        {
                            if (conceptos_por_venta.id == concepto_por_nota_credito.id_conceptos_por_venta)
                                conceptos_por_venta.cantidad -= concepto_por_nota_credito.cantidad.Value;
                        }
                    }
                    /* *** *** *** *** *** *** *** ***  Buscar si hay algun descuento aplicado a esta venta *** *** *** *** *** *** */
                    descuento descuento = db.descuento.FirstOrDefault(x => x.id_venta == venta.id && x.monto > 0);
                    if (descuento != null)
                    {
                        ViewBag.existe_descuento = true;
                        ViewBag.descuento = descuento;
                    }
                    else
                        ViewBag.existe_descuento = false;



                    ViewBag.Venta = venta;
                    ViewBag.ListaConceptos = ListaConceptosVenta;

POS/Views/NotaCredito/ModalCargandoPDF.cshtml
<div id="page-content" style="background: #fff; padding: 0px; margin-top: -20px;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Creando PDF</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.ModalCargandoPDF .modal-dialog').css('width', '20%');
    });
</script>

POS/Views/NotaCredito/NuevaNotaCredito.cshtml
@{
    ViewBag.Title = "POS - Nueva Nota De Credito";
}

<div id="page-content" style="background: #fff;">
    <h3 class="title-hero" style="text-align: center; background-color: #254054; color: white;">Nueva Nota De Credito</h3>
    <div class="example-box-wrapper" style="margin-top: -10px; margin-bottom: 10px; border-left: 1px solid rgba(37, 64, 84, 0.45); border-right: 1px solid rgba(37, 64, 84, 0.45); border-bottom: 1px solid rgba(37, 64, 84, 0.45);">
        <table id="TablaNotasCredito" class="table" style="width: 100%;">
            <tbody>
                <tr>
                    <td style="width: 150px; text-align: right; border: 0px; font-weight:bold;">ID Venta: </td>
                    <td style="width: 25%; border: 0px;">
                        <input type="text" id="venta" class="form-control" style="text-transform:uppercase" />
                    </td>
                    <td style="border: 0px;"></td>
                    <td style="border: 0px;"></td>
                    <td style="border: 0px;"></td>
                    <td style="border: 0px;"></td>
                </tr>
            </tbody>
        </table>
        <div id="VistaParcial"></div>
        <a id="BotonAgregarNotaCredito" class="btn btn-success" style="margin-bottom:10px; margin-left:10px; display:none;">
            <span class="glyph-icon icon-separator">
                <i class="glyph-icon icon-check"></i>
            </span>
            <span class="button-content">Aceptar</span>
        </a>
        <a href="@Url.Action("Index")" class="btn btn-danger" style="margin-bottom:10px; margin-left:10px;">
            <span class="glyph-icon icon-separator">
                <i class="glyph-icon icon-times"></i>
            </span>
            <span class="button-content">Cancelar</span>
        </a>
    </div>
</div>

<div id="Ticket" style="display: none"></div>

<script type="text/javascript">
    $(document).ready(function () {
        /*CONFIGURACIONES*/
        if ($('#configuracion_caja_centralizada').val() == "True") {
            caja_centralizada = true;
        } else {
            caja_centralizada = false;
        }
        if ($('#configuracion_edicion_precios').val() == "True") {
            editar_precio_dinamicamente = true;
        } else {
            editar_precio_dinamicamente = false;
        }
        if ($('#configuracion_imprimir_solo_ticket').val() == "True") {
            impresion_solo_ticket = true;
        } else {
            impresion_solo_ticket = false;
        }
        if ($('#confirmacion_directa').val() == "True") {
            confirmacion_directa = true;
        } else {
            confirmacion_directa = false;
        }
        /*CONFIGURACIONES*/
        $('#BotonAgregarNotaCredito').click(function () {
            var NotaCredito = [];
            NotaCredito.push({
                id: "",
                id_sucursal: parseInt($('#id_sucursal').val()),
                id_venta: parseInt($('#id_venta').val())
            });
            var Conceptos = [];
            $(".Seleccionado").each(function () {
                Conceptos.push({
                    id: $(this).find('.concepto').val(),
                    cantidad: $(this).find('.cantidad').val()
                });
            });
            var params = {
                'nota_credito': NotaCredito[0],
                'ListaConceptos': Conceptos
            };
            var url = '@Url.Action("NuevaNotaCredito")';
            $.ajax({
                url: url,
                type: "POST",
                contentType: 'application/json;',
                data: JSON.stringify(params),
                success: function (respuesta) {
                    ConfiguracionImpresionNotaCredito(respuesta.id);
                },
                async: "false"
            });
        });
    });
    $(document).on('change', '#venta', function () {
        var url = '@Url.Action("VistaParcialNuevaNotaCredito")';
        $.ajax({
            url: url,
            type: "POST",
            data: { id_venta: $(this).val() },
            success: function (vista) {
                $('#VistaParcial').html(vista);
            },
            async: "false"
        });
    });
    $(document).on('click', '.SeleccionarConcepto', function () {
        if ($(this).is(':checked')) {
            $(this).parent().parent().addClass('Seleccionado');
            $(this).parent().parent().css('background-color', 'rgb(255, 87, 87)');
            $(this).parent().parent().css('color', 'white');
            $(this).parent().parent().find('.cantidad').attr('readonly', null);
            $(this).parent().parent().find('.cantidad').focus();
        } else {
            $(this).parent().parent().removeClass('Seleccionado');
            $(this).parent().parent().css('background-color', 'white');
            $(this).parent().parent().css('color', '');
            $(this).parent().parent().find('.cantidad').attr('readonly', 'readonly');
        }
        VerificarSeleccionados();
    });
    $(document).on('keyup', '.cantidad', function () {
        VerificarSeleccionados();
    });
    function VerificarSeleccionados() {
        if ($('.concepto:checked').length > 0) {
            var mostrar = true;
            $('.cantidad').each(function () {
                if (($(this).val() == "" || parseFloat($(this).val()) == 0) && $(this).parent().prev().children().is(':checked')) {
                    mostrar = false;
                }
            });
            if (mostrar) {
                $('#BotonAgregarNotaCredito').show();
            } else {
                $('#BotonAgregarNotaCredito').hide();
            }
        } else {
            $('#BotonAgregarNotaCredito').hide();
        }
    }
</script>

@*FUNCIONES PARA IMPRIMIR TICKET O PDF DE LA NOTA DE CREDITO*@
<script type="text/javascript">
    var id_nota_credito = 0;
    var cantidad_tickets = parseInt($('#configuracion_cantidad_tickets').val());;
    function ConfiguracionImpresionNotaCredito(id) {
        id_nota_credito = id;
        if (impresion_solo_ticket) {
            try {
                GenerarTicketNotaCredito();
            } catch (e) {
                var url = '@Url.Action("ModalAdvertenciaImpresionNoMozilla", "Venta")';
                $.ajax({
                    url: url,
                    data: {},
                    success: function (VistaParcial) {
                        bootbox.dialog({
                            className: "ModalAdvertenciaImpresionNoMozilla",
                            message: VistaParcial,
                            closeButton: false,
                            onEscape: true
                        });
                    },
                    async: false
                });
            }
        } else {
            EscogerModoImpresionNotaCredito();
        }
    }
    function EscogerModoImpresionNotaCredito(){
        var url = '@Url.Action("ModalSeleccionarModoImpresion", "printer")';
        $.ajax({
            url: url,
            data: { },
            success: function (VistaParcial) {
                bootbox.dialog({
                    className: "ModalSeleccionarModoImpresion ModalSeleccionarModoImpresionNotaCredito",
                    message: VistaParcial,
                    closeButton: false,
                    onEscape: true
                });
            },
            async: false
        });
    }
    $(document).on('click', '.ModalSeleccionarModoImpresionNotaCredito #selectPDF', function () {
        window.open('@Url.Action("GenerarPDFNotaCredito", "NotaCredito", new { id = "_id_" })'.replace("_id_", id_nota_credito));
        $(".ModalSeleccionarModoImpresion").modal("hide");
        bootbox.hideAll();
        window.location.reload(true);
    });
    $(document).on('click', '.ModalSeleccionarModoImpresionNotaCredito #selectTicketPrinter', function () {
        try {
            $(".ModalSeleccionarModoImpresion").modal("hide");
            GenerarTicketNotaCredito();
        } catch (e) {
            var url = '@Url.Action("ModalAdvertenciaImpresionNoMozilla", "Venta")';
            $.ajax({
                url: url,
                data: {},
                success: function (VistaParcial) {
                    bootbox.dialog({
                        className: "ModalAdvertenciaImpresionNoMozilla",
                        message: VistaParcial,
                        closeButton: false,
                        onEscape: true
                    });
                },
                async: false
            });
        }
    });
    function GenerarTicketNotaCredito() {
        cantidad_tickets = parseInt(cantidad_tickets);
        if (isNaN(cantidad_tickets)) {
            cantidad_tickets = 1;
        }
        var url = '@Url.Action("VistaParcialGenerarTicketNotaCredito", "NotaCredito")';
        $.ajax({
            url: url,
            data: { id: id_nota_credito },
            success: function (VistaParcial) {
                $("#Ticket").html(VistaParcial);
                for (var i = 0; i < cantidad_tickets; i++) {
                    ImprimirTicketNotaCredito(document.getElementById('Ticket'));
                }
            },
            async: false
        });
        //ESTA FUNCION SOLO SE NECESITA SI NO SIRVE CARGAR LA VISTA PARCIAL PARA HACER OTRA NOTA DE CREDITO
        window.location.reload(true);
        //ESTA FUNCION SOLO SE NECESITA SI NO SIRVE CARGAR LA VISTA PARCIAL PARA HACER OTRA NOTA DE CREDITO
    }
    function ImprimirTicketNotaCredito(Ticket) {
        jsPrintSetup.setSilentPrint(true);
        var content = Ticket.innerHTML
        jsPrintSetup.setOption('marginTop', 5);
        jsPrintSetup.setOption('marginBottom', 15);
        jsPrintSetup.setOption('marginLeft', 5);
        jsPrintSetup.setOption('marginRight', 5);
        // set page header
        jsPrintSetup.setOption('headerStrLeft', '');
        jsPrintSetup.setOption('headerStrCenter', '');
        jsPrintSetup.setOption('headerStrRight', '');
        // set empty page footer
        jsPrintSetup.setOption('footerStrLeft', '');
        jsPrintSetup.setOption('footerStrCenter', '');
        jsPrintSetup.setOption('footerStrRight', '');
        jsPrintSetup.definePaperSize(101, 101, "Custom", "Custom_Paper", "Custom PAPER", 300, 400, jsPrintSetup.kPaperSizeMillimeters);
        jsPrintSetup.setPaperSizeData(101);
        //pwin.document.open();
        w = window.open();
        w.document.write(content);
        w.print();
        w.close();
        //setTimeout(function () { pwin.close(); }, 1000);
        jsPrintSetup.setSilentPrint(false);
    }
    //ESTA FUNCION SOLO SE NECESITA SI NO SIRVE CARGAR LA VISTA PARCIAL PARA HACER OTRA NOTA DE CREDITO
    $(document).on('click', '.ModalAdvertenciaImpresionNoMozilla #BotonAceptarAdvertencia', function () {
        window.location.reload(true);
    });
    //ESTA FUNCION SOLO SE NECESITA SI NO SIRVE CARGAR LA VISTA PARCIAL PARA HACER OTRA NOTA DE CREDITO
</script>
@*FUNCIONES PARA IMPRIMIR TICKET O PDF DE LA NOTA DE CREDITO*@

POS/Views/NotaCredito/VistaParcialGenerarTicketNotaCredito.cshtml
@model POS.Models.nota_credito
@{
    POS.Models.configuracion_general configuracion_general = POS.Fn.Configuracion.TraerConfiguracionGeneral();
}

<table style="max-width: 320px; font-size: 16px; font-family: Arial; line-height: 16px;">
    <tr>
        <td colspan="4" style="text-align: center;">
            <img src="@Url.Content("/UploadFolder/logo/" + configuracion_general.logo)" style="max-width:300px; max-height:200px;"  />
        </td>
    </tr>
    <tr>
        <td colspan="2">NOTA DE CREDITO:</td>
        <td colspan="2" style="text-transform: uppercase;">@POS.Fn.Numeros.serie_folio_by_id_nota_credito(Model.id)</td>
    </tr>
    <tr>
        <td colspan="2">VENTA:</td>
        <td colspan="2" style="text-transform: uppercase;">@POS.Fn.Numeros.serie_folio_by_id(Model.id_venta)</td>
    </tr>
    <tr>
        <td colspan="2">FECHA DE CREACION:</td>
        <td colspan="2" style="text-transform: uppercase;">@Model.fecha_creacion.Value.ToString("dd/MM/yyyy HH:mm:ss")</td>
    </tr>
    @if (Model.id_estatus_nota_credito == 2)
    {
        <tr>
            <td colspan="2">VENTA APLICADA:</td>
            <td colspan="2" style="text-transform: uppercase;">@POS.Fn.Numeros.serie_folio_by_id(Model.id_venta)</td>
        </tr>
        <tr>
            <td colspan="2">FECHA DE USO:</td>
            <td colspan="2" style="text-transform: uppercase;">@Model.fecha_uso.Value.ToString("dd/MM/yyyy HH:mm:ss")</td>
        </tr>
    }
    else if (Model.id_estatus_nota_credito == 3)
    {
        <tr>
            <td colspan="2">FECHA DE CANCELACION:</td>
            <td colspan="2" style="text-transform: uppercase;">@Model.fecha_cancelacion.Value.ToString("dd/MM/yyyy HH:mm:ss")</td>
        </tr>
    }
    <tr>
        <td colspan="2">ESTATUS:</td>
        <td colspan="2" style="text-transform: uppercase;">@Model.estatus_nota_credito.nombre</td>
    </tr>
    <tr>
        <td colspan="2">CLIENTE:</td>
        <td colspan="2" style="text-transform: uppercase;">@Model.venta.cliente.Razon_social</td>
    </tr>
    <tr>
        <td colspan="2">VENDEDOR:</td>
        <td colspan="2" style="text-transform: uppercase;">@Model.usuario_punto_venta.nombre_usuario</td>
    </tr>
    <tr>
        <td colspan="4" style="text-align: center">________________________________________________</td>
    </tr>
    <tr>
        <td colspan="4" style="height: 10px;"></td>
    </tr>
    <tr>
        <td colspan="2">CANTIDAD A FAVOR:</td>
        <td colspan="2" style="text-transform: uppercase;"><span>$</span>@Model.cantidad.Value</td>
    </tr>
    <tr>
</table>